export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import { Alert } from "@/components/general/Alert";
import "../globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="a/* r" dir="rtl">
      <body suppressHydrationWarning={true}>
        <Alert />
        {children}
      </body>
    </html>
  );
}
