import type { Metadata } from "next";
import ".././globals.css";
import Navbar from "@/components/Header/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body >
          <Navbar/>
        {children}
        <footer>
          footer
        </footer>
        </body>
    </html>
  );
}
